-- view-schema for the sql database. this file is converted into a
-- string constant, as the symbol:
-- 
-- char const views_constant[...] = { ... };
--
-- and emitted as views.h at compile time. it is used by
-- database.cc when opening an sqlite db.
--
-- views have no structural affect on the database, so we delete and
-- rebuild them every time we open the db (along with adding the
-- functions we're interested in). the schema migration is thus 
-- never concerned with changes to views.

