/* Automatically generated.  Do not edit */
/* See the mkopcodeh.awk script for details */
#define OP_MemLoad                     1
#define OP_HexBlob                     131
#define OP_Column                      2
#define OP_SetCookie                   3
#define OP_Real                        130
#define OP_MoveGt                      4
#define OP_Ge                          77
#define OP_AggFocus                    5
#define OP_RowKey                      6
#define OP_IdxRecno                    7
#define OP_AggNext                     8
#define OP_Eq                          73
#define OP_OpenWrite                   9
#define OP_NotNull                     71
#define OP_If                          10
#define OP_PutStrKey                   11
#define OP_String8                     92
#define OP_Pop                         12
#define OP_SortPut                     13
#define OP_CollSeq                     14
#define OP_OpenRead                    15
#define OP_SortReset                   16
#define OP_AutoCommit                  17
#define OP_Gt                          74
#define OP_Sort                        18
#define OP_ListRewind                  19
#define OP_IntegrityCk                 20
#define OP_Function                    21
#define OP_Subtract                    84
#define OP_And                         65
#define OP_Noop                        22
#define OP_Return                      23
#define OP_Remainder                   87
#define OP_Multiply                    85
#define OP_Variable                    24
#define OP_String                      25
#define OP_ParseSchema                 26
#define OP_PutIntKey                   27
#define OP_AggFunc                     28
#define OP_Close                       29
#define OP_ListWrite                   30
#define OP_CreateIndex                 31
#define OP_IsUnique                    32
#define OP_IdxIsNull                   33
#define OP_NotFound                    34
#define OP_MustBeInt                   35
#define OP_Halt                        36
#define OP_IdxLT                       37
#define OP_AddImm                      38
#define OP_Statement                   39
#define OP_RowData                     40
#define OP_MemMax                      41
#define OP_Push                        42
#define OP_Or                          64
#define OP_KeyAsData                   43
#define OP_NotExists                   44
#define OP_OpenTemp                    45
#define OP_MemIncr                     46
#define OP_Gosub                       47
#define OP_Divide                      86
#define OP_AggSet                      48
#define OP_Integer                     49
#define OP_SortNext                    50
#define OP_Prev                        51
#define OP_Concat                      88
#define OP_BitAnd                      79
#define OP_CreateTable                 52
#define OP_Last                        53
#define OP_IsNull                      70
#define OP_ShiftRight                  82
#define OP_ResetCount                  54
#define OP_Callback                    55
#define OP_ContextPush                 56
#define OP_DropTrigger                 57
#define OP_DropIndex                   58
#define OP_FullKey                     59
#define OP_IdxGE                       60
#define OP_IdxDelete                   61
#define OP_Vacuum                      62
#define OP_MoveLe                      63
#define OP_IfNot                       67
#define OP_DropTable                   68
#define OP_MakeRecord                  69
#define OP_Delete                      78
#define OP_ListRead                    90
#define OP_ListReset                   93
#define OP_ShiftLeft                   81
#define OP_Dup                         94
#define OP_Goto                        95
#define OP_Clear                       96
#define OP_IdxGT                       97
#define OP_MoveLt                      98
#define OP_Le                          75
#define OP_CursorStore                 99
#define OP_VerifyCookie                100
#define OP_Pull                        101
#define OP_Not                         66
#define OP_SetNumColumns               102
#define OP_AbsValue                    103
#define OP_Transaction                 104
#define OP_Negative                    89
#define OP_Ne                          72
#define OP_CursorLoad                  105
#define OP_AggGet                      106
#define OP_ContextPop                  107
#define OP_BitOr                       80
#define OP_Next                        108
#define OP_AggInit                     109
#define OP_Distinct                    110
#define OP_NewRecno                    111
#define OP_Lt                          76
#define OP_AggReset                    112
#define OP_Destroy                     113
#define OP_ReadCookie                  114
#define OP_ForceInt                    115
#define OP_IdxColumn                   116
#define OP_Recno                       117
#define OP_OpenPseudo                  118
#define OP_Blob                        119
#define OP_Add                         83
#define OP_MemStore                    120
#define OP_Rewind                      121
#define OP_MoveGe                      122
#define OP_IdxPut                      123
#define OP_BitNot                      91
#define OP_Found                       124
#define OP_NullRow                     125
